# set base image (host OS)
FROM python:3.8

# set the working directory in the container
WORKDIR /HPE

EXPOSE 8501

ENTRYPOINT ["streamlit", "run"]
# command to run on container start
CMD [ "HPE_Proj.py" ]
