apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aks-1b61"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aks-1b61"
  template:
    metadata:
      labels:
        app: "aks-1b61"
    spec:
      containers:
        - name: "aks-1b61"
          image: "aksteam3registery.azurecr.io/aks"
          ports:
          - containerPort: 8501