apiVersion: v1
kind: Service
metadata:
    name: "streamlitaks-d630"
    labels:
        app: "streamlitaks-d630"
spec:
    type: ClusterIP
    ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: http
    selector:
        app: "streamlitaks-d630"