on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: aksteam3.azurecr.io
        username: ${{ secrets.acr_aksteam3_username }}
        password: ${{ secrets.acr_aksteam3_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "DockerFile" -t aksteam3.azurecr.io/aks:${{ github.sha }} --label dockerfile-path=DockerFile
        docker push aksteam3.azurecr.io/aks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep aks8286 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace aks8286`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: aks8286
        container-registry-url: aksteam3.azurecr.io
        container-registry-username: ${{ secrets.acr_aksteam3_username }}
        container-registry-password: ${{ secrets.acr_aksteam3_password }}
        secret-name: aksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: aks8286
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          aksteam3.azurecr.io/aks:${{ github.sha }}
        imagepullsecrets: |
          aksdockerauth
